feat: integrations

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,8 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+echo "🛠️  Running lint-staged..."
 
-npx --no-install lint-staged
-npx -p prettier@latest -p pretty-quick
+npx lint-staged
+if [ $? -ne 0 ]; then
+  echo "🚨  lint-staged failed"
+  exit 1
+fi
+echo "🛠️✅  lint-staged passed"
